INSERT INTO source (id, description,name) VALUES 
(1, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM NAUKRI WEBSITE','NAUKRI'),
(2, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM TIMES.COM WEBSITE','TIMES'),
(3, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM MONISTER.COM WEBSITE','MONISTER'),
(4, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM LINKDIN WEBSITE','LINKDIN'),
(5, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM REFFERLS FROM OUR EMPLOYEES','REFFER'),
(6, 'WE CAN DOWNLOAD THE CANDIDATE RESUME FROM OTHER RESOURCES','OTHERS');