INSERT INTO permission(id,name,description,role_id) VALUES 
(1, 'home','This is for home',1),
(2, 'job','This is for job',1),
(3, 'candidate','This is for candidate',1),
(4, 'client','This is for client',1),
(5, 'vendor','This is for vendor',1),
(6, 'email','This is for email',1),
(7, 'settings','This is for settings',1),
(8, 'uploadfile','This is for upload',1),
(9, 'home','This is for home',2),
(10, 'candidate','This is for candidate',2),
(11, 'job','This is for job',2),
(12, 'candidate','This is for candidate',3),
(13, 'home','This is for home',3),
(14, 'home','This is for home',4),
(15, 'candidate','This is for candidate',4);